export const carRentalDetails = [
    {
        "id": 123,
        "carName" : "Hyundai Grand i10",
        "imageUrl" : "https://stimg.cardekho.com/images/carexteriorimages/630x420/Hyundai/Grand-i10/7715/1585572310544/front-left-side-47.jpg",
        "maxCapacity" :"4", 
        "rent" : "450",
        'color' :'Red',
        "vehicleNo" : "MH 20 66 8989",
        "fuelType" :"Petrol",
        "engineModel" :"Kappa 20212",
        "description" : "When it’s about excitement and sheer road dominance, the Swift certainly knows how to make its presence felt. Its Floating Roof Design, solid shoulder lines, rich side body sculpting and Precision Cut Alloy Wheels, all unite to create a machine that’s simply crafted to thrill.",
        "bookingDetails" : {
            "isBooked" : false,
            "name" : "",
            "phoneNumber" : "",
            "issueDate" :"",
            "returnDate" :"",
        }
    },
    {
        "id": 234,
        "carName" : "Ford EcoSport",
        "imageUrl" : "https://www.india.ford.com/content/dam/Ford/website-assets/ap/in/nameplate/ecosport/gallery-new/exterior%20overlays/Technology-overlay.jpg",
        "maxCapacity" :"5", 
        "rent" : "650",
        'color' :'Brown',
        "vehicleNo" : "DL 20 66 4583",
        "fuelType" :"Disel",
        "engineModel" :"Meta 20212",
        "description" : "Gear up for more fun, more style, and more thrill with the Ford EcoSport. Experience a whole new perspective, the ease of technology, superior comfort, and a greener tomorrow with BS VI compliant engines. And, set out on a journey that leads you to discover more in you.",
        "bookingDetails" : {
            "isBooked" : true,
            "name" : "Jon Doe",
            "phoneNumber" : "+91 8978987898",
            "issueDate" :"2020-05-13",
            "returnDate" :"2020-05-25",
        }
    },
    {
        "id": 345,
        "carName" : "Honda CRV",
        "imageUrl" : "https://www.hondacarindia.com/areas/crv/content/desktop/images/gallery/grid5_pop.jpg",
        "maxCapacity" :"5", 
        "rent" : "750",
        'color' :'Brown',
        "vehicleNo" : "MH 20 25 4040",
        "fuelType" :"Petrol",
        "engineModel" :"Titan 5473",
        "description" : "The evolutionary design of the grille is marked with sharp lines & fine cuts. It tells the story of a bold & charismatic leader. The sharp LED headlamp with the stunning DRL merges smoothly with the lines of the grille. It looks you straight ",
        "bookingDetails" : {
            "isBooked" : false,
            "name" : "",
            "phoneNumber" : "",
            "issueDate" :"",
            "returnDate" :"",
        }
    },
    {
        "id": 567,
        "carName" : "Honda City",
        "imageUrl" : "https://www.hondacarindia.com/areas/city/content/desktop/images/new-honda-city.jpg",
        "maxCapacity" :"4", 
        "rent" : "400",
        'color' :'silver',
        "vehicleNo" : "UP 20 66 9262",
        "fuelType" :"Petrol",
        "engineModel" :"1.5 Litres i-VTEC ",
        "description" : "The classic Honda City contour is unmistakable but the surprises will thrill you too. It is a design vision that echoes the City’s blue blooded sedan charm. A look that adds panache and exhilaration to the game. It is an overpowering presence that meets a brand new attitude.",
        "bookingDetails" : {
            "isBooked" : false,
            "name" : "",
            "phoneNumber" : "",
            "issueDate" :"",
            "returnDate" :"",
        }
    },
]
