export const carRentalDetails = [
    {
        "id": 123,
        "carName" : "Maruti Suzuki Swift Desire",
        "imageUrl" : "https://stimg.cardekho.com/images/carexteriorimages/630x420/Hyundai/Grand-i10/7715/1585572310544/front-left-side-47.jpg",
        "maxCapacity" :"4", 
        "rent" : "450",
        'color' :'red',
        "vehicleNo" : "MH 20 66 8989",
        "fuelType" :"Petrol",
        "engineModel" :"Kappa 20212",
        "description" : "When it’s about excitement and sheer road dominance, the Swift certainly knows how to make its presence felt. Its Floating Roof Design, solid shoulder lines, rich side body sculpting and Precision Cut Alloy Wheels, all unite to create a machine that’s simply crafted to thrill.",
        "bookingDetails" : {
            "isBooked" : false,
            "name" : "",
            "phoneNumber" : "",
            "issueDate" :"",
            "returnDate" :"",
        }
    },
    {
        "id": 234,
        "carName" : "Maruti Suzuki Swift Desire",
        "imageUrl" : "https://media.zigcdn.com/media/model/2019/Sep/maruti-swift_600x400.jpg",
        "color ": "Red",
        "maxCapacity" :"4", 
        "rent" : "450",
        'color' :'red',
        "vehicleNo" : "MH 20 66 8989",
        "fuelType" :"Petrol",
        "engineModel" :"Kappa 20212",
        "description" : "When it’s about excitement and sheer road dominance, the Swift certainly knows how to make its presence felt. Its Floating Roof Design, solid shoulder lines, rich side body sculpting and Precision Cut Alloy Wheels, all unite to create a machine that’s simply crafted to thrill.",
        "bookingDetails" : {
            "isBooked" : true,
            "name" : "Jon Doe",
            "phoneNumber" : "+91 8978987898",
            "issueDate" :"2020-05-13",
            "returnDate" :"2020-05-25",
        }
    },
    {
        "id": 345,
        "carName" : "Maruti Suzuki Swift Desire",
        "imageUrl" : "https://media.zigcdn.com/media/model/2019/Sep/maruti-swift_600x400.jpg",
        "color ": "Red",
        "maxCapacity" :"4", 
        "rent" : "450",
        'color' :'red',
        "vehicleNo" : "MH 20 66 8989",
        "fuelType" :"Petrol",
        "engineModel" :"Kappa 20212",
        "description" : "When it’s about excitement and sheer road dominance, the Swift certainly knows how to make its presence felt. Its Floating Roof Design, solid shoulder lines, rich side body sculpting and Precision Cut Alloy Wheels, all unite to create a machine that’s simply crafted to thrill.",
        "bookingDetails" : {
            "isBooked" : false,
            "name" : "",
            "phoneNumber" : "",
            "issueDate" :"",
            "returnDate" :"",
        }
    },
    {
        "id": 567,
        "carName" : "Maruti Suzuki Swift Desire",
        "imageUrl" : "https://media.zigcdn.com/media/model/2019/Sep/maruti-swift_600x400.jpg",
        "color ": "Red",
        "maxCapacity" :"4", 
        "rent" : "450",
        'color' :'red',
        "vehicleNo" : "MH 20 66 8989",
        "fuelType" :"Petrol",
        "engineModel" :"Kappa 20212",
        "description" : "When it’s about excitement and sheer road dominance, the Swift certainly knows how to make its presence felt. Its Floating Roof Design, solid shoulder lines, rich side body sculpting and Precision Cut Alloy Wheels, all unite to create a machine that’s simply crafted to thrill.",
        "bookingDetails" : {
            "isBooked" : false,
            "name" : "",
            "phoneNumber" : "",
            "issueDate" :"",
            "returnDate" :"",
        }
    },
]
